version: '3.8'

services:
  tv-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: yjiang/tv-server
    restart: unless-stopped
    ports:
      - "10101:10101"
    volumes:
      - ./config.json:/config.json
    environment:
      - MONGO_URI=mongodb://root:123456@mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo

volumes:
  mongodb_data:
